accounts/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'accounts'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    ]
        

baseball/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'baseball'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),


    path('board/', views.PostListView.as_view(), name='board'),
    path('board/<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('board/new/', views.PostCreateView.as_view(), name='create_post'),
    path('board/<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('board/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),

    path('team_info/', views.team_info, name='team_info'),
    path('team_info/<int:year>', views.team_info_year, name='team_info_year'),
    
    path('game_info/', views.game_info, name='game_info'),
    path('game_info/<int:date>', views.game_info_date, name='game_info_date'),
    
    
    path('game_info/preview/<int:date>/<int:today_game_num>', views.preview_old, name='preview'),
    path('game_info/lineup/<int:date>/<int:today_game_num>', views.lineup, name='lineup'),
    path('game_info/boxscore/<int:date>/<int:today_game_num>', views.boxscore, name='boxscore'),
    path('game_info/sp_graph/<int:date>/<int:today_game_num>', views.SpGraphView.as_view(), name='sp_graph'),
    path('game_info/run_graph/<int:date>/<int:today_game_num>', views.RunGraphView.as_view(), name='run_graph'),
    
    ]
        

config/urls.py
from django.contrib import admin
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import include, path
# ---------------------------------------------------------------------------------------- #
from config import settings

import mimetypes


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    
    # ---------------------------------------------------------------------------------------- #
    path('baseball/',include('baseball.urls')),
    path('accounts/', include('accounts.urls')),
    path('upbit/', include('upbit.urls')),
    path('bithumb/', include('bithumb.urls'))

]

# ------------------------------------------ [debug] --------------------------------------------- #
if settings.DEBUG:
    mimetypes.add_type("application/javascript", ".js", True)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path

from . import views



app_name = 'main'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.to_main, name='to_main'),
    path('main/', views.index, name='index'),]

baseball/views.py
# 장고 패키지
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import AuthUser, TeamInfo, GameInfo, TeamGameInfo, ScoreRecord, BatterRecord, PitcherRecord, TodayGameInfo, TodayTeamGameInfo, TodayLineUp, TodayToTo, RunGraphData, UpdateTime, Post
# 데이터용 패키지
from django.db.models import Q
# 그래프용 패키지
from rest_framework.response import Response
from rest_framework.views import APIView
from django.views.generic import View
#제네릭 뷰
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


import json
import time
import numpy as np
# ---------------------------------------------------------------------------------------- #

def index(request):
    context = {'index': 'Hello'}
    return render(request,'baseball/index.html',context)
    
def team_info(request):
    '''
    team_list = TeamInfo.objects.all()
    context = {'team_list':team_list}
    '''
    return render(request,'baseball/team_info.html')
    
def team_info_year(request, year):
    '''
    연도별 team_info 데이터 불러오는 view
    '''
    team_year_set = TeamInfo.objects.filter(year__contains = year)
    rank = 1
    last_win_rate = 0
    max_predicted_win = 0
    for i,team_year in enumerate(team_year_set):
        
        win_rate = team_year.win_rate
        if win_rate != last_win_rate:
            rank = i+1
        team_year.rank = rank
        last_win_rate = win_rate

        matched_count = team_year.win + team_year.draw + team_year.lose
        last_count = 144 - matched_count
        predicted_win = team_year.win + last_count * 0.5
        max_predicted_win = max(max_predicted_win, predicted_win)
        team_year.predicted_win = predicted_win
    
    for i,team_year in enumerate(team_year_set):
        difference_1st = max_predicted_win - team_year.predicted_win
        team_year.difference_1st = difference_1st


    context = {'team_year_set':team_year_set,'year':year}
    return render(request,'baseball/team_info_year.html',context)


def game_info(request):
    local_time = time.localtime()
    year = str(local_time[0])
    month = str(local_time[1]).zfill(2)
    day = str(local_time[2]).zfill(2)
    today = f'{year}-{month}-{day}'
    
    try:
        TGI = TodayGameInfo.objects.all()
        last_date = TGI[0].game_idx[:8]
    except:
        GI = GameInfo.objects.all()
        last_date = GI.last().game_idx[:8]
    last_date = last_date[:4]+"-" + last_date[4:6] + "-" +last_date[6:8]
    
    UDT = UpdateTime.objects.all().order_by('-date','-craw_time')
    date = UDT[0].date#list(game_date_dic.values('etc')[0].values())[0]
    craw_time = UDT[0].craw_time
    context = {'today':today,'date':date, 'craw_time':craw_time,'last_date': last_date}
    
    
    return render(request,'baseball/game_info.html',context)
    
def game_info_date(request,date):
    '''
    특정날짜에 진행되는 경기들의 데이터를 가져옴
    
    '''
    game_date_set = GameInfo.objects.filter(game_idx__contains = str(date)).values()
    game_date_idx = game_date_set.values('game_idx')
    
    team_game_dic = TeamGameInfo.objects.filter(game_idx__in = game_date_idx).values()
    team_game_idx = team_game_dic.values("team_game_idx","home_away")
    is_end = True
    
    
    if game_date_set.exists():
        pass
    else:
        game_date_set = TodayGameInfo.objects.filter(game_idx__contains = str(date)).values()
        game_date_idx = game_date_set.values('game_idx')
        team_game_dic = TodayTeamGameInfo.objects.filter(game_idx__in = game_date_idx).values()
        team_game_idx = team_game_dic.values("team_game_idx","home_away")
        is_end = False
        
    
    for game_num_idx, game_date in enumerate(game_date_set):
        
        game_date['game_num_idx'] = game_num_idx+1
        game_date['away_url'] = "/static/images/emblem/emblem_" + game_date['away_name'] + ".png";
        game_date['home_url'] = "/static/images/emblem/emblem_" + game_date['home_name'] + ".png";
        
        
        game_idx = game_num_idx * 2
        if team_game_idx[game_idx]['home_away'] == 'home':
            home_idx = team_game_idx[game_idx]['team_game_idx']
            away_idx = team_game_idx[game_idx+1]['team_game_idx']

        else:
            home_idx = team_game_idx[game_idx+1]['team_game_idx']
            away_idx = team_game_idx[game_idx]['team_game_idx']
        
        
        print(home_idx, away_idx)
        if is_end:
            home_score_dic = ScoreRecord.objects.filter(team_game_idx = home_idx).values()
            away_score_dic = ScoreRecord.objects.filter(team_game_idx = away_idx).values()
            
            game_date['home_score'] = home_score_dic[0]['r']
            game_date['away_score'] = away_score_dic[0]['r']
    
            home_pitcher = PitcherRecord.objects.filter(team_game_idx = home_idx).values()[0]['name']
            away_pitcher = PitcherRecord.objects.filter(team_game_idx = away_idx).values()[0]['name']
    
            game_date['home_pitcher'] = home_pitcher
            game_date['away_pitcher'] = away_pitcher
        else:
            try:
                home_pitcher = TodayLineUp.objects.filter(team_game_idx = home_idx).values()[0]['name']
                away_pitcher = TodayLineUp.objects.filter(team_game_idx = away_idx).values()[0]['name']
                game_date['home_pitcher'] = home_pitcher
                game_date['away_pitcher'] = away_pitcher
            except:
                pass
            pass
    
    data_length = game_date_set.count()
    #print(game_date_set)
    context = {'game_date_set':game_date_set,'is_end':is_end, 'data_length':data_length}
    return render(request,'baseball/game_info_date.html',context)



class RunGraphView(APIView):
    
    def __init__(self):

        self.year = int 

        self.home_name = str
        self.away_name = str

        self.home_set = None
        self.away_set = None

        
    def set_data(self, request, date, today_game_num, team_or_foe = 'team'):
        today_game_num_idx_min = (2*today_game_num)-2
        today_game_num_idx_max = (2*today_game_num)
        
        if TodayGameInfo.objects.filter(game_idx__contains = str(date)).exists():
            
            TGI = TodayTeamGameInfo
            GI = TodayGameInfo
            
        else:
            
            TGI = TeamGameInfo
            GI = GameInfo
            
        
        game_date_set = GI.objects.filter(game_idx__contains = str(date))
        today_game_idx = game_date_set.values("game_idx")
        
        team_game_set = TGI.objects.filter(game_idx__in = today_game_idx)
        today_game_set = team_game_set[today_game_num_idx_min:today_game_num_idx_max]
        

        year = int(str(date)[:4])
        self.year = year

        home_team_num = today_game_set[1].team_num
        away_team_num = today_game_set[0].team_num
        
        self.home_name = game_date_set[today_game_num-1].home_name
        self.away_name = game_date_set[today_game_num-1].away_name
        

        home_game_num = today_game_set[1].game_num
        away_game_num = today_game_set[0].game_num
        if team_or_foe == 'team':
            self.home_set = TeamGameInfo.objects.select_related('scorerecord').filter(year = year, team_num= home_team_num)
            self.away_set = TeamGameInfo.objects.select_related('scorerecord').filter(year = year, team_num= away_team_num)
        
        else:
            self.home_set = TeamGameInfo.objects.select_related('scorerecord').filter(year = year, foe_num= home_team_num)
            self.away_set = TeamGameInfo.objects.select_related('scorerecord').filter(year = year, foe_num= away_team_num)
            
    def get_run_dist(self, score_set):
            run_list = [0 for i in range(16)]
            length= score_set.count()
            
            for score in score_set:
                run = round(score.scorerecord.r)
                
                if run >=15:
                    run_list[-1]+=1
                else:
                    run_list[run]+=1
                    
            
            result_list= list()
            count = 0
            run_sum = 0
            for run in run_list:
                
                run_sum+=run
                count+=1
                if count == 2:
                    if length == 0:
                        result_list.append(0)
                    else:
                        result_list.append(run_sum / length*100)
                    count = 0
                    run_sum = 0 
                
            return result_list

    def get_run_range(self, score_set, game_range):
            length = score_set.count()
            score_list = list()
            temp_score_list = list()
            range_score = 0
            for i,score in enumerate(score_set):
                now_score = score.scorerecord.r
                temp_score_list.append(now_score)
                range_score+= now_score
                if i >= game_range:
                    range_score-= temp_score_list[i - game_range]
                devide = game_range if i >= game_range else i + 1 
                score_list.append(round(range_score / devide,3))
            
            return score_list

    

    def get(self,request,date,today_game_num):
        
        self.set_data(request, date, today_game_num)

        year = self.year
        home_name = self.home_name
        away_name = self.away_name

        home_set = self.home_set
        away_set = self.away_set
     
        home_dic = dict()
        home_dic['dist'] = self.get_run_dist(home_set)
        home_dic['range_run'] = self.get_run_range(home_set, 5)
        home_dic['name'] = home_name

        away_dic = dict()
        away_dic['dist'] = self.get_run_dist(away_set)

templates/baseball/board/create.html
<!-- templates/create.html -->
{% extends "base.html" %}


{% block content %}

<head>
    <meta charset="UTF-8">
    <title>글쓰기</title>
<style>
    .board-container {
    max-width: 1000px;
    margin: 50px auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    }

    .board-form-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .board-form-title {
        font-weight: bold;
        font-size: 1.5em;
        margin-bottom: 30px;
    }

    .board-label {
        display: block;
        margin-top: 10px;
    }

    .board-input[type="text"],
    .board-textarea {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .board-textarea {
        height: 500px;
    }

    .board-button {
        margin-top: 20px;
        padding: 10px 20px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .board-button:hover {
        background-color: #0056b3;
    }

    .board-a {
        display: inline-block;
        margin-top: 20px;
        text-decoration: none;
        color: #007bff;
    }

    .board-a:hover {
        text-decoration: underline;
    }
    
</style>
    
</head>
<body>
    <div class="container board-container">
        <div class="board-form-header">
            <div class="board-form-title">글쓰기</div>
        </div>
        <form action="{% url 'baseball:create_post' %}" method="post">
            {% csrf_token %}
            <label for="title" class="board-label">제목</label>
            <input type="text" id="title" name="title" class="board-input" required>
            <label for="content" class="board-label">내용</label>
            <textarea id="content" name="content" class="board-textarea" required></textarea>
            <button type="submit" class="board-button">작성</button>


        </form>
        <button href="{% url 'baseball:board' %}" class="board-button">목록으로 돌아가기</button>
    </div>
</body>
</html>

{% endblock %}

templates/baseball/board/delete.html
<!-- templates/delete.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 삭제</title>
</head>
<body>
    <h1>글 삭제</h1>
    <p>{{ post.title }}를 삭제하시겠습니까?</p>
    <form action="{% url 'baseball:delete_post' post.post_id %}" method="post">
        {% csrf_token %}
        <button type="submit">삭제</button>
        <a href="{% url 'baseball:detail_post' post.post_id %}">취소</a>
    </form>
</body>
</html>

templates/baseball/board/detail.html
<!-- board/templates/board/detail.html -->
{% extends "base.html" %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .post-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
        .post-box {
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 30px;
            margin-top: 20px;
            background-color: #ffffff;
        }
        .post-title {
            font-size: 1.5rem;
            font-weight: bold;
            margin-bottom: 20px;
        }
        .post-meta {
            font-size: 0.9rem;
            
            margin-bottom: 20px;
        }
        .post-content {
            font-size: 1.1rem;
            
            margin-top: 50px;
            
        }
        hr {
        border: 0;
        border-top: 1px solid #ccc;
        margin: 10px 0;
    }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="post-box">
            <div class="post-header">
                <div class="post-title">{{ post.title }}</div>
                {% if edit_button %}
                 
                <div>
                    <a href="{% url 'baseball:update_post' post.post_id %}">수정</a>
                </div>
                <div>
                    <a href="{% url 'baseball:delete_post' post.post_id %}">삭제</a>
                </div>
                {% endif %}
                <div class="post-meta">
                    작성자: {{ post.user_id }} | 작성일: {{ post.created_at|date:"Y-m-d H:i" }}
                </div>
            </div>
            <hr>
            <div class="post-content">
                {{ post.content }}
            </div>
        </div>
        <a href="{% url 'baseball:board' %}" class="btn btn-primary mt-3">목록으로 돌아가기</a>
    </div>
    <div>
        
            

        
    </div>
</body>


</html>

{% endblock %}

templates/baseball/board/list.html
{% extends "base.html" %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>게시판</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .col{
            text-align: center;
        }

        .col-number {
            width: 5%;
        }
        .col-title {
            width: 70%;
        }
        .col-date {
            width: 15%;
        }
        .col-writer {
            width: 10%;
        }
        

    </style>
</head>
<body>
    <div class="container mt-5">
        <h4 class="mb-4">자유게시판</h4>
        <table class="table table-bordered table-hover">
            <thead class="thead-light" >
                <tr>
                    <th class = "col col-number">번호</th>
                    <th class = "col col-title">제목</th>
                    <th class = "col col-writer">작성자</th>
                    <th class = "col col-date">작성일</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'baseball:detail_post' post.post_id %}">{{ post.title }}</a></td>
                    
                    
                    <td>{{post.user_id}}</td>
                    <td>{{ post.created_at|date:"Y-m-d H:i" }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if user.is_authenticated %}
            <a href="{% url 'baseball:create_post' %}">글쓰기</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">글쓰기</a>
            
        {% endif %}
        
    </div>

</html>

{% endblock %}

templates/baseball/board/update.html
<!-- templates/update.html -->
{% extends "base.html" %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>수정하기</title>
    <style>
        .board-container {
        max-width: 1000px;
        margin: 50px auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        }
    
        .board-form-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
    
        .board-form-title {
            font-weight: bold;
            font-size: 1.5em;
            margin-bottom: 30px;
        }
    
        .board-label {
            display: block;
            margin-top: 10px;
        }
    
        .board-input[type="text"],
        .board-textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
    
        .board-textarea {
            height: 500px;
        }
    
        .board-button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    
        .board-button:hover {
            background-color: #0056b3;
        }
    
        .board-a {
            display: inline-block;
            margin-top: 20px;
            text-decoration: none;
            color: #007bff;
        }
    
        .board-a:hover {
            text-decoration: underline;
        }
        
    </style>
</head>
<body>
    <div class="board-container">
        <div class="board-form-header">
            <div class="board-form-title">수정하기</div>
        </div>
        <form action="{% url 'baseball:update_post' post.post_id %}" method="post">
            {% csrf_token %}
            <label for="title" class="board-label">제목</label>
            <input type="text" id="title" name="title" value="{{ post.title }}" required>
            <label for="content" class="board-label">내용</label>
            <textarea id="content" name="content" class="board-textarea" required>{{ post.content }}</textarea>
            <button type="submit" class="board-button">작성</button>
            
        </form>
        <button href="{% url 'baseball:board' %}" class="board-button">목록으로 돌아가기</button>
    </div>
</body>
</html>

{% endblock %}