bithumb/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'bithumb'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),
    path('trade_list/', views.trade_list, name='trade_list'),
    path('trade_list/trade_bithumb/', views.trade_bithumb, name='trade_bithumb'),
    path('trade_list/trade_bitget/', views.trade_bitget, name='trade_bitget'),
    path('trade_list/trade_bitget/user-memos/', views.get_user_memos, name='get_user_memos'),
    path('trade_list/trade_bitget/user-memos/update', views.update_user_memo, name='update_user_memo')

    ]
        

config/urls.py
from django.contrib import admin
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import include, path
# ---------------------------------------------------------------------------------------- #
from config import settings

import mimetypes


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    
    # ---------------------------------------------------------------------------------------- #
    path('baseball/',include('baseball.urls')),
    path('accounts/', include('accounts.urls')),
    path('upbit/', include('upbit.urls')),
    path('bithumb/', include('bithumb.urls'))

]

# ------------------------------------------ [debug] --------------------------------------------- #
if settings.DEBUG:
    mimetypes.add_type("application/javascript", ".js", True)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path

from . import views



app_name = 'main'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.to_main, name='to_main'),
    path('main/', views.index, name='index'),]

upbit/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'upbit'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),
    path('trade_list/', views.trade_list, name='trade_list'),
    path('trade_list/trade_info/', views.trade_info, name='trade_info'),
    path('trade_list/trade_day/', views.trade_day, name='trade_day'),
    path('trade_list/trade_swing/', views.trade_swing, name='trade_swing'),
    path('trade_list/trade_timetable/', views.trade_timetable, name='trade_timetable'),
    #path('get_market_data/', views.get_market_data, name='get_market_data'),
    ]
        

bithumb/views.py
from django.shortcuts import render
from .models import Market, MarketHour, MarketDay, MarketInfo, MADays, MA60Minutes, MarketBitget, MA60MinutesBitget, MarketHourBitget, UserMemo
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_http_methods

from django.db.models import DateTimeField, ExpressionWrapper, IntegerField
from django.db.models import Sum, F, Count, Max, Min
from django.db.models.functions import TruncHour, ExtractHour, Floor, TruncDate
from django.db.models.expressions import F
from django.db import connection
from collections import defaultdict
from datetime import datetime, timedelta, timezone
# Create your views here.
def index(request):
    context = {'index': 'Hello'}
    return render(request,'bithumb/index.html',context)
def trade_list(request):
    context = {'index': 'Hello'}
    return render(request,'bithumb/trade_list.html',context)


def get_current_time(current_time: datetime, modify_seconds: int) -> str:   
    '''
    현재시간을 10초 단위로 맞춰서 변화해주는 함수
    '''
    # 10초 단위로 내림
    rounded_seconds = (current_time.second // 10) * 10
    
    # 기본 시간 설정 (초만 변경)
    base_time = current_time.replace(
        second=rounded_seconds, 
        microsecond=0
    )
    
    # 양수/음수에 따라 시간 조정
    if modify_seconds < 0:
        adjusted_time = base_time - timedelta(seconds=abs(modify_seconds))
    else:
        adjusted_time = base_time + timedelta(seconds=abs(modify_seconds))
    
    return adjusted_time


def trade_bithumb(request):
    
    
    TEST_SECONDS= 0
    #current_time = datetime(2025, 2, 11, 23, 14, 41, tzinfo = timezone.utc)#datetime.now(tzinfo = timezone.utc) #- timedelta(minutes = TEST_SECONDS)
    current_time = datetime.now(tz = timezone.utc) - timedelta(seconds = 10)
    #current_time = datetime(2025, 2, 12, 8, 1, 33, tzinfo = timezone.utc)
    last_time = get_current_time(current_time, -(TEST_SECONDS))
    last_temp_time = get_current_time(current_time, -(10 + TEST_SECONDS))
    last_1_time = get_current_time(current_time, -(60 + TEST_SECONDS))
    last_5_time = get_current_time(current_time, -(300 + TEST_SECONDS))
    last_10_time = get_current_time(current_time, -(600 + TEST_SECONDS))
    last_30_time = get_current_time(current_time, -(1800 + TEST_SECONDS))
    last_60_time = get_current_time(current_time, -(3600 + TEST_SECONDS))
    last_240_time = get_current_time(current_time, -(14400 + TEST_SECONDS))
    
    
    last_1d_time = get_current_time(current_time, -(60 * 60 * 24 +TEST_SECONDS))
    last_7d_time = get_current_time(current_time, -(60 * 60 * 24 * 7 +TEST_SECONDS))
    
    utc_00_time = get_current_time(current_time.replace(hour= 0, minute = 0, second = 0 ,microsecond = 0),0)
    
    #시점데이터
    last_data = Market.objects.filter(log_dt = last_time)
    if len(last_data)== 0:
        last_data = MarketBitget.objects.filter(log_dt = last_temp_time)        
    last_1_data = Market.objects.filter(log_dt = last_1_time)
    last_5_data = Market.objects.filter(log_dt = last_5_time)
    last_30_data = Market.objects.filter(log_dt = last_30_time)
    last_60_data = Market.objects.filter(log_dt = last_60_time)
    last_240_data = Market.objects.filter(log_dt = last_240_time)
    last_1d_data = Market.objects.filter(log_dt = last_1d_time)
    last_7d_data = Market.objects.filter(log_dt = last_7d_time)


    market_info_data = MarketInfo.objects.all().order_by('market')
    
    #고점데이터
    today_high_low_data = Market.objects.filter(log_dt__gte= last_1d_time).values('market').annotate(max_price = Max('price'), min_price = Min('price'))
    
    #print(last_3_sum_data)
    # 직전 n~60분 데이터 -> 나중에 수정해보자 좋은값찾아서
    # last_1_60_sum_data = Market.objects.filter(log_dt__lt= last_1_time, log_dt__gte= last_60_time, volume__gt = 0).values('market').annotate(total_volume=Sum('volume'), total_amount = Sum('amount'), cnt = Count('volume')).order_by('market')
    # last_3_60_sum_data = Market.objects.filter(log_dt__lt= last_3_time, log_dt__gte= last_60_time, volume__gt = 0).values('market').annotate(total_volume=Sum('volume'), total_amount = Sum('amount'), cnt = Count('volume')).order_by('market')
    # last_5_60_sum_data = Market.objects.filter(log_dt__lt= last_5_time, log_dt__gte= last_60_time, volume__gt = 0).values('market').annotate(total_volume=Sum('volume'), total_amount = Sum('amount'), cnt = Count('volume')).order_by('market')
    # last_10_60_sum_data = Market.objects.filter(log_dt__lt= last_10_time, log_dt__gte= last_60_time, volume__gt = 0).values('market').annotate(total_volume=Sum('volume'), total_amount = Sum('amount'), cnt = Count('volume')).order_by('market')
    
    
    last_hour = (last_time.replace(minute=0, second=0, microsecond=0) - timedelta(hours=1))
    last_day = (last_time- timedelta(days=1)).date()
    
    ma_60_data = MA60Minutes.objects.filter(log_dt = last_hour).order_by('market')
    ma_day_data = MADays.objects.filter(date = last_day).order_by('market')


    print('last_time:', last_time, len(last_data))
    print('last_hour:', last_hour, len(ma_60_data))
    print('last_day:', last_day, len(ma_day_data))
    


    
    market_list = [
        {
            'market': item.market[4:],
            # 'korean_name':item.korean_name,
            # 'english_name':item.english_name,
            # 'issue_month': item.issue_month,
            # 'listing_month': item.listing_month,

            # 'capitalization':next((d.capitalization for d in market_supply_list if d.symbol == item.symbol), None),
            # 'max_supply':next((d.max_supply for d in market_supply_list if d.symbol == item.symbol), None),
            # 'now_supply':next((d.now_supply for d in market_supply_list if d.symbol == item.symbol), None),


            # 'kimchi_premium': next((d.price_foreign for d in last_data if d.market == item.market), None),
            'capitalization': next((d.capitalization for d in market_info_data if d.market == item.market), None),
            'price_last': next((d.price for d in last_data if d.market == item.market), None),
            'price_1m': next((d.price for d in last_1_data if d.market == item.market), None),
            'price_5m': next((d.price for d in last_5_data if d.market == item.market), None),
            'price_30m': next((d.price for d in last_30_data if d.market == item.market), None),
            'price_60m': next((d.price for d in last_60_data if d.market == item.market), None),
            'price_240m': next((d.price for d in last_240_data if d.market == item.market), None),
            'price_1d': next((d.price for d in last_1d_data if d.market == item.market), None),
            'price_7d': next((d.price for d in last_7d_data if d.market == item.market), None),
            

            'price_today_high': next((d['max_price'] for d in today_high_low_data if d['market'] == item.market), None),
            'price_today_low': next((d['min_price'] for d in today_high_low_data if d['market'] == item.market), None),
            
            
            
            
            'ma_60_10': next((d.ma_10 for d in ma_60_data if d.market == item.market), None),
            'ma_60_20': next((d.ma_20 for d in ma_60_data if d.market == item.market), None),
            'ma_60_34': next((d.ma_34 for d in ma_60_data if d.market == item.market), None),
            'ma_60_50': next((d.ma_50 for d in ma_60_data if d.market == item.market), None),
            'ma_60_100': next((d.ma_100 for d in ma_60_data if d.market == item.market), None),
            'ma_60_200': next((d.ma_200 for d in ma_60_data if d.market == item.market), None),
            'ma_60_400': next((d.ma_400 for d in ma_60_data if d.market == item.market), None),
            'ma_60_800': next((d.ma_800 for d in ma_60_data if d.market == item.market), None),

            'ma_day_10': next((d.ma_10 for d in ma_day_data if d.market == item.market), None),
            'ma_day_20': next((d.ma_20 for d in ma_day_data if d.market == item.market), None),
            'ma_day_34': next((d.ma_34 for d in ma_day_data if d.market == item.market), None),
            'ma_day_50': next((d.ma_50 for d in ma_day_data if d.market == item.market), None),
            'ma_day_100': next((d.ma_100 for d in ma_day_data if d.market == item.market), None),
            'ma_day_200': next((d.ma_200 for d in ma_day_data if d.market == item.market), None),
            
            
            

            # 'amount_1m': next((d['total_amount'] for d in last_1_sum_data if d['market'] == item.market), None),
            # 'amount_5m': next((d['total_amount'] for d in last_5_sum_data if d['market'] == item.market), None),
            # 'amount_10m': next((d['total_amount'] for d in last_10_sum_data if d['market'] == item.market), None),
            # 'amount_60m': next((d['total_amount'] for d in last_60_sum_data if d['market'] == item.market), None),
            # 'amount_1440m': next((d['total_amount'] for d in last_1440_sum_data if d['market'] == item.market), None),
            # 'amount_today': next((d['total_amount'] for d in last_today_sum_data if d['market'] == item.market), None),

            # 'count_1m': next((d['cnt'] for d in last_1_sum_data if d['market'] == item.market), None),
            # 'count_5m': next((d['cnt'] for d in last_5_sum_data if d['market'] == item.market), None),
            # 'count_10m': next((d['cnt'] for d in last_10_sum_data if d['market'] == item.market), None),
            # 'count_60m': next((d['cnt'] for d in last_60_sum_data if d['market'] == item.market), None),
            # 'count_1440m': next((d['cnt'] for d in last_1440_sum_data if d['market'] == item.market), None),
            # 'count_today': next((d['cnt'] for d in last_today_sum_data if d['market'] == item.market), None),

        }
        for item in market_info_data
        ]

    print(market_list[0])
    context = {'trade_day_data': market_list}
    

templates/bithumb/index.html
{% extends "base.html" %}



{% block content %}
{{index}}

{% endblock %}

templates/bithumb/trade_day.html
<div class="table-container">
    
    <table id="dataTableTradeToday" class="display">
        <thead>
            <tr>
                <th colspan="5">기본정보</th>
                <th colspan="7">가격</th>
                <th colspan="3">거래량</th>
                <th colspan="4">거래대금</th>
                <th colspan="3">RSI</th>

            </tr>
            <tr>
                <th>종목</th>
                <th>이름</th>
                <th>시총</th>
                <th>김프</th>
                <th>현재가</th>

                <th>5분</th>
                <th>30분</th>
                <th>60분</th>
                <th>240분</th>
                <th>고점</th>
                <th>저점</th>
                <th>범위</th>

                <th>1분</th>
                <th>5분</th>
                <th>60분</th>
                
                <th>1분</th>
                <th>5분</th>
                <th>60분</th>
                <th>오늘</th>
                
                <th>5분</th>
                <th>15분</th>
                <th>60분</th>
            </tr>
        </thead>
    </table>
</div>

templates/bithumb/trade_day_old.html
<title>Market Data</title>
<style>
    .table-container {
        margin: 20px;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    table.dataTable thead th {
        background-color: #f8f9fa;
        font-weight: bold;
    }

    .highlight {
        background-color: #ffeeba;
        transition: background-color 2s;
    }
    .positive {
        color: #FF3B30;  /* 빨간색 */
    }
    .negative {
        
        color: #0a60ff;  /* 파란색 */
    }
    
   .dataTables_wrapper {
        width: 100%;
        max-width: 100%;
        overflow-x: auto;
    }
    #marketTable {
        width: 100% !important;
        font-size: 13px;
    }
</style>

<div class="table-container">
    <table id="marketTable" class="display">
        <thead>
            <tr>
                <th colspan="8">기본정보</th>
                <th colspan="6">가격(n분 전 대비 현재가격)</th>
                <th colspan="3">거래량(직전 60분 평균 대비 n분 변화량)</th>
                <th colspan="4">거래대금</th>

            </tr>
            <tr>
                <th>종목</th>
                <th>이름</th>
                <th>시총</th>
                <th>발행률</th>
                <th>발행일</th>
                <th>상장일</th>
                <th>현재가</th>
                <th>김프</th>

                <th>5분</th>
                <th>30분</th>
                <th>60분</th>
                <th>240분</th>
                <th>고점</th>
                <th>저점</th>

                <th>1분</th>
                <th>5분</th>
                <th>10분</th>
                <th>1분</th>
                <th>5분</th>
                <th>60분</th>
                <th>오늘</th>
                
            </tr>
        </thead>
        <tbody>
            
            {% for market in trade_day_data %}
            
            
            <tr>
                <!--데이터 들어오는 자리-->
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    let dataTable;
    
    $(document).ready(function() {
        dataTable = $('#marketTable').DataTable({
            
            pageLength: 200,            // 페이지당 10개 표시
            order: [[16, 'desc']],      // 1분 거래대금 기준 내림차순 정렬
            responsive: true, // 반응형 디자인 활성화
             
            language: {
                search: "검색:",
                //lengthMenu: "페이지당 _MENU_ 개",
                
                info: "_TOTAL_개 중 _START_ - _END_",
                paginate: {
                    first: "처음",
                    last: "마지막",
                    next: "다음",
                    previous: "이전"
                },
                zeroRecords: "검색 결과가 없습니다."
            },
            

            columnDefs: [ 
            

            {
                targets: '_all', // 모든 컬럼에 적용
                sortSequence: ['desc', 'asc',null],
                width: '5%'
            },
            {
                targets: 2, // 시가총액 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        if (data == null || isNaN(data)) return '0억';
                            return Number(data).toLocaleString() + '억';
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            },
           
            {
                targets: 6, // 현재가격 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        
                        return Number(data).toLocaleString();
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            },
            {
                targets: 17, // 1분 거래대금 열 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        return data + '억';
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            },
            {
                targets: 18, // 5분 거래대금 열 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        return data + '억';
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            },
            {
                targets: 19, // 60분 거래대금 열 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        return data + '억';
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            },
            {
                targets: 20, // 오늘 전체 거래대금 열 인덱스
                render: function(data, type, row) {
                    if (type === 'display') {
                        return data + '억';
                    } else if (type === 'sort') {
                        return parseFloat(data);
                    }
                    return data;
                },
                
            }
            ],
            
        });

        console.log("Fetching new data...");

        
        refreshData()
        setInterval(refreshData, 20000); // 600s = 1분
    });
    `${item.supply_ratio}%`
    
    function priceData(item) {
        item.price_ratio_5m = (((item.price_1m - item.price_5m) / item.price_5m)*100).toFixed(2)
        item.price_ratio_30m = (((item.price_1m - item.price_30m) / item.price_30m)*100).toFixed(2)
        item.price_ratio_60m = (((item.price_1m - item.price_60m) / item.price_60m)*100).toFixed(2)
        item.price_ratio_240m = (((item.price_1m - item.price_240m)/ item.price_240m)*100).toFixed(2)
        item.price_ratio_high = (((item.price_1m - item.price_today_high)/ item.price_today_high)*100).toFixed(2)
        item.price_ratio_low = (((item.price_1m - item.price_today_low)/ item.price_today_low)*100).toFixed(2)
        
        item.supply_ratio = !item.max_supply ? '-' : `${((item.now_supply / item.max_supply)*100).toFixed(1)}%`
        return item
    }
    function volumeData(item){
        item.volume_ratio_1m_60m = (item.ratio_1m_60m*100).toFixed(1)
        item.volume_ratio_3m_60m = (item.ratio_3m_60m*100).toFixed(1)
        item.volume_ratio_5m_60m = (item.ratio_5m_60m*100).toFixed(1)
        item.volume_ratio_10m_60m = (item.ratio_10m_60m*100).toFixed(1)
                            
        return item
    }

    function capitalizationData(item){
        item.capitalization = (item.capitalization / 100000000).toFixed(0)

        return item
    }

    function formatRatio(ratio) {
        const value = parseFloat(ratio);
        if (value > 0) {
            return `<span class="positive">+${ratio}%</span>`;
        } else if (value < 0) {
            return `<span class="negative">${ratio}%</span>`;
        }
        return `${ratio}%`;
    }
    function formatBillions(number, decimal_place) {
         return (number / 100000000).toFixed(decimal_place);
    }
    function formatMillions(number, decimal_place) {
         return (number / 1000000).toFixed(decimal_place);
    }
    function calculateAverages(data) {
        const averages = {
            market: '평균',
            korean_name: '',
            ratio_5m: data.reduce((sum, item) => sum + parseFloat(item.ratio_5m), 0) / data.length,
            ratio_30m: data.reduce((sum, item) => sum + parseFloat(item.ratio_30m), 0) / data.length,
            ratio_60m: data.reduce((sum, item) => sum + parseFloat(item.ratio_60m), 0) / data.length,
            ratio_240m: data.reduce((sum, item) => sum + parseFloat(item.ratio_240m), 0) / data.length,
            ratio_1m_60m: data.reduce((sum, item) => sum + parseFloat(item.ratio_1m_60m), 0) / data.length,
            ratio_5m_60m: data.reduce((sum, item) => sum + parseFloat(item.ratio_5m_60m), 0) / data.length,
            ratio_10m_60m: data.reduce((sum, item) => sum + parseFloat(item.ratio_10m_60m), 0) / data.length,
        };
        return averages;
    }


    function refreshData() {
        
        $.ajax({
            url: "{% url 'upbit:trade_day' %}",
            method: 'GET',
            headers: {
            'X-Requested-With': 'XMLHttpRequest'
        },
            success: function(data) {
                console.log("데이터 수신:", data);  // 데이터 확인
                
                if (dataTable) {
                    // 기존 데이터 삭제
                    dataTable.clear();

                    
                    // forEach로 데이터 추가
                    data.forEach(function(item) {
                        item = priceData(item)
                        item = volumeData(item)
                        item = capitalizationData(item)
                        console.log("처리된 아이템:", item);
                        dataTable.row.add([
                            `<a href="https://www.upbit.com/exchange?code=CRIX.UPBIT.${item.market}" target="_blank" style="color: #000000; text-decoration: none;">${item.market}</a>`,
                            item.korean_name,
                            item.capitalization,
                            item.supply_ratio,
                            item.issue_month,
                            item.listing_month,

                            item.price_1m,
                            formatRatio(item.kimchi_premium),
                            formatRatio(item.price_ratio_5m),

                            formatRatio(item.price_ratio_30m),
                            formatRatio(item.price_ratio_60m),
                            formatRatio(item.price_ratio_240m),
                            formatRatio(item.price_ratio_high),
                            formatRatio(item.price_ratio_low),

                            formatRatio(item.volume_ratio_1m_60m),
                            formatRatio(item.volume_ratio_5m_60m),
                            formatRatio(item.volume_ratio_10m_60m),
                            formatBillions(item.amount_1m,1),
                            formatBillions(item.amount_5m,1),
                            formatBillions(item.amount_60m,1),
                            formatBillions(item.amount_today,1)
                            
                            
                            
                        ]);
                    });
                    
                    // 테이블 다시 그리기
                    dataTable.draw();
                    
                }
            },
            error: function(err) {
                console.error("데이터 가져오기 실패:", err);
            }
        });
    }
</script>

templates/bithumb/trade_info.html
<div class="table-container">
    <table id="dataTableTradeInfo" class="display">
        <thead>
            
            <tr>
                <th>종목</th>
                <th>이름</th>
                <th>시총</th>
                <th>발행률</th>
                <th>발행일</th>
                <th>상장일</th>
                <th>Chain</th>
                <th>Category</th>
                <th>Focus</th>
                <th>Country</th>
                <th>비고</th>


                
                
            </tr>
        </thead>
    </table>
</div>

templates/bithumb/trade_swing.html
<div class="table-container">
    <table id="dataTableTradeSwing" class="display">
        <thead>
            <tr>
                <th colspan="5">기본정보</th>
                <th colspan="7">가격</th>
                <th colspan="3">거래량</th>
                <th colspan="3">거래대금</th>
                <th colspan="2">RSI</th>

            </tr>
            <tr>
                <th>종목</th>
                <th>이름</th>
                <th>시총</th>
                <th>김프</th>
                <th>현재가</th>

                <th>1일</th>
                <th>3일</th>
                <th>7일</th>
                <th>28일</th>
                <th>고점</th>
                <th>저점</th>
                <th>범위</th>

                <th>1일</th>
                <th>3일</th>
                <th>7일</th>

                <th>1일</th>
                <th>3일</th>
                <th>7일</th>
                
                
                <th>240분</th>
                <th>1일</th>
                
            </tr>
        </thead>
    </table>
</div>

templates/bithumb/trade_timetable.html
<div class="table-container">
    
    <table id="dataTableTradeTimetable" class="display">
        <thead>
            <tr>
                <th colspan="3">기본정보</th>
                <th colspan="12">가격변화</th>
                

            </tr>
            <tr>
                <th>종목</th>
                <th>이름</th>
                <th>현재가</th>

                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>

                <th>6</th>
                <th>7</th>
                <th>8</th>
                <th>9</th>
                <th>10</th>
                <th>11</th>
                <th>12</th>                
                
                
            </tr>
        </thead>
    </table>
</div>