accounts/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'accounts'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    ]
        

baseball/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'baseball'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),


    path('board/', views.PostListView.as_view(), name='board'),
    path('board/<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('board/new/', views.PostCreateView.as_view(), name='create_post'),
    path('board/<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('board/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),

    path('team_info/', views.team_info, name='team_info'),
    path('team_info/<int:year>', views.team_info_year, name='team_info_year'),
    
    path('game_info/', views.game_info, name='game_info'),
    path('game_info/<int:date>', views.game_info_date, name='game_info_date'),
    
    
    path('game_info/preview/<int:date>/<int:today_game_num>', views.preview_old, name='preview'),
    path('game_info/lineup/<int:date>/<int:today_game_num>', views.lineup, name='lineup'),
    path('game_info/boxscore/<int:date>/<int:today_game_num>', views.boxscore, name='boxscore'),
    path('game_info/sp_graph/<int:date>/<int:today_game_num>', views.SpGraphView.as_view(), name='sp_graph'),
    path('game_info/run_graph/<int:date>/<int:today_game_num>', views.RunGraphView.as_view(), name='run_graph'),
    
    ]
        

bithumb/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'bithumb'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),
    path('trade_list/', views.trade_list, name='trade_list'),
    path('trade_list/trade_bithumb/', views.trade_bithumb, name='trade_bithumb'),
    path('trade_list/trade_bitget/', views.trade_bitget, name='trade_bitget'),
    path('trade_list/trade_bitget/user-memos/', views.get_user_memos, name='get_user_memos'),
    path('trade_list/trade_bitget/user-memos/update', views.update_user_memo, name='update_user_memo')

    ]
        

config/urls.py
from django.contrib import admin
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import include, path
# ---------------------------------------------------------------------------------------- #
from config import settings

import mimetypes


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    
    # ---------------------------------------------------------------------------------------- #
    path('baseball/',include('baseball.urls')),
    path('accounts/', include('accounts.urls')),
    path('upbit/', include('upbit.urls')),
    path('bithumb/', include('bithumb.urls'))

]

# ------------------------------------------ [debug] --------------------------------------------- #
if settings.DEBUG:
    mimetypes.add_type("application/javascript", ".js", True)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path

from . import views



app_name = 'main'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.to_main, name='to_main'),
    path('main/', views.index, name='index'),]

upbit/urls.py
# ---------------------------------------- [edit] ---------------------------------------- #
from django.urls import path, include

from . import views




app_name = 'upbit'


# ---------------------------------------------------------------------------------------- #
urlpatterns = [
    # ---------------------------------------- [edit] ---------------------------------------- #
    path('', views.index, name='index'),
    path('trade_list/', views.trade_list, name='trade_list'),
    path('trade_list/trade_info/', views.trade_info, name='trade_info'),
    path('trade_list/trade_day/', views.trade_day, name='trade_day'),
    path('trade_list/trade_swing/', views.trade_swing, name='trade_swing'),
    path('trade_list/trade_timetable/', views.trade_timetable, name='trade_timetable'),
    #path('get_market_data/', views.get_market_data, name='get_market_data'),
    ]
        

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.sessions.models import Session


# ---------------------------------------------------------------------------------------- #

def to_main(request):
    return redirect('/main')
def index(request):
    # ---------------------------------------- [edit] ---------------------------------------- #
    '''
    메인화면
    '''
    num_list = [0,1,2]
    context = {'num_list': num_list}
    return render(request, 'main.html', context)
    
    # ---------------------------------------------------------------------------------------- #

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <title>
            Baseball with LYC
        </title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->


        
        

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        
        <!-- Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        
        <!-- jQuery JS -->
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>

        <!--moment JS-->
        <script src="https://momentjs.com/downloads/moment.js"></script>

        <!-- FontAweSome CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

        <!--Custom CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        
        <!--highcharts CSS&JS-->
        <script src="{% static 'highcharts.js' %}" ></script>
        <link rel="stylesheet" type="text/css" href="{% static 'highcharts.css' %}">
        
        <!--데이터 테이블 관련 CSS&JS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    </head>



    <body>
        
        <div class="wrap-container">   
            {% include "navbar.html" %}
         
                {% block content %}            
                {% endblock %}
        </div>
        
        


    </body>

    
</html>

templates/main.html
{% extends 'base.html' %}

{% block content %}




<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner" >
    <div class="carousel-item main-001 active" data-interval=2500 >
      <img src="../static/images/main/baseball_main_001.jpg" class="d-block w-100" alt="main-001" >
    </div>
    <div class="carousel-item main-002" data-interval=2500 >
      <img src="../static/images/main/baseball_main_002.jpg" class="d-block w-100" alt="main-002">
    </div>
    <div class="carousel-item main-003" data-interval=2500 >
      <img src="../static/images/main/baseball_main_003.jpg" class="d-block w-100" alt="main-003">
      
    </div>
  </div>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
  </a>
</div>




{% endblock %}

templates/navbar.html
 <!-- 네비게이션바 -->
<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container-fluid">
        <ul class="navbar-nav me-auto">

            <li class="nav-item">
                <a class="nav-link mb-0 h2" href="{%url 'main:index'%}" ><h>Home</h></a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link mb-0 h2" href="{%url 'upbit:trade_list' %}" ><h>Upbit</h></a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link mb-0 h2" href="{%url 'bithumb:trade_list' %}" ><h>Bitcoin</h></a>
            </li>
            <li class="nav-item">
                <a class="nav-link mb-0 h2" href="{%url 'baseball:index' %}" ><h>Baseball</h></a>
            </li>
            <li class="nav-item">
                <a class="nav-link mb-0 h5" href="{% url 'baseball:team_info' %}" ><b>팀순위</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link mb-0 h5" href="{% url 'baseball:game_info' %}" ><b>게임정보</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link mb-0 h5" href="{% url 'baseball:board' %}" ><b>게시판</b></a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <p class="nav-link mb-0 h5">Hello, {{ user.username }}! <a href="{% url 'accounts:logout' %}">Logout</a></p>
                {% else %}
                    <p class="nav-link mb-0 h5"><a href="{% url 'accounts:login' %}">Login</a></p>
                {% endif %}
            </li>
            
        </ul>
        
        <div class="nav-item">
            <span class="navbar-text">
                {{active_users}}명
            </span>
        </div>
        
        
    </div>
</nav>


    